"""add course and enrollment fields

Revision ID: 56de9d9c869d
Revises: 9985fc4b1ca0
Create Date: 2026-08-19 16:05:30.305942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56de9d9c869d'
down_revision = '9985fc4b1ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instructor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['instructor_id'], ['id'])

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_course_student', ['course_id', 'student_id'])
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_course_student', type_='unique')
        batch_op.drop_column('student_id')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('instructor_id')
        batch_op.drop_column('capacity')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
