"""add users.email_confirmed

Revision ID: 76ce22289b8a
Revises: 8f06c41b4372
Create Date: 2026-08-24 16:55:57.043870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76ce22289b8a'
down_revision = '8f06c41b4372'
branch_labels = None
depends_on = None


def upgrade():
    # server_default para que los usuarios ya existentes no rompan el
    # NOT NULL (quedan como no confirmados, que es lo esperado)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'email_confirmed', sa.Boolean(), nullable=False,
            server_default=sa.false()
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
